name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta todos los días a medianoche UTC

  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push Snake
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
